

const DashboardMain = () => {
    return (
        <section className="">
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
            <h1>DashboardMain</h1>
        </section>
    )
}

export default DashboardMain